name: alien_signals
description: The lightest signal library - Dart implementation of alien-signals.
version: 0.0.12
repository: https://github.com/medz/alien-signals-dart

environment:
  sdk: ^3.5.0

topics:
  - signal
  - signals
  - reactive
  - alien-signals
  - state

funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.12
  reactivity_benchmark: ^0.0.1
