name: alien_signals
description: The lightest signal library - Dart implementation of alien-signals.
version: 0.0.4
repository: https://github.com/medz/alien-signals-dart

environment:
  sdk: ^3.5.0

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.12
