name: _
publish_to: none

environment:
  sdk: ^3.5.0

workspace:
  - pub/alien_signals
  - pub/flutter_alien_signals
  - pub/flutter_alien_signals/example

dev_dependencies:
  reactivity_benchmark: ^0.0.1
