name: flutter_alien_signals
description: "A new Flutter package project."
version: 0.0.1
repository: https://github.com/medz/alien-signals-dart

topics:
  - signal
  - signals
  - reactive
  - alien-signals
  - state

funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe

resolution: workspace
environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
