name: alien_signals_bench
publish_to: none
environment:
  sdk: ^3.6.0

dependencies:
  alien_signals:
    path: ../
  dart_reactivity_benchmark:
    git:
      url: https://github.com/medz/dart-reactivity-benchmark
      ref: main

dependency_overrides:
  alien_signals:
    path: ../
