name: testing

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sdk: [stable, 3.5, 3.6, 3.7]

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub get
      - run: dart analyze
      - run: dart test
