name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: dart pub get
      - run: dart analyze
      - run: dart test pub/alien_signals/test
      - run: flutter test pub/flutter_alien_signals/test
